pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    path('new_comment/', views.new_comment, name='new_comment'),

]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pizzas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=75)
    picture = models.ImageField(upload_to='img',blank=True,null=True)

    class Meta:
        verbose_name_plural = 'pizzas'

    def __str__(self):
        return self.pizza_name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.TextField()

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment_text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    user_name = models.TextField()
    
    class Meta:
        verbose_name_plural =  'comments'

    def __str__(self):
        return self.comment_text + ' ' + self.date_added + ' ' + self.user_name

pizzas/forms.py
from django import forms
from .models import Comment

class Comment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']
        labels = {'comment_text':''}
        widgets = {'comment_text': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza
from .forms import Comment

# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'pizzas':pizzas}

    return render(request,'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    picture = Pizza.picture

    context = {'pizza':pizza,'toppings':toppings}

    return render(request, 'pizzas/pizza.html', context)

def new_comment(request, pizza_id):
    #topic_id is definedi n the url so it needs to be defined here as well
    pizza = Pizza.objects.get(id=pizza_id)
    #Uppercase T topic because it imports it form .models at the top of this file
    #lower case tpoic is just a variable name

    if request.method != 'POST':
        form = Comment()
    else:
        form = Comment(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    context = {'form':form}
    return render(request, 'pizzas/new_comment.html', context)

pizzas/templates/pizzas/base.html
<p style="font-size:75px;color:red">
    <a href="{% url 'pizzas:index' %}">Big Papa's Pipin' Hot Pizzeria</a>
</p>
<p style="font-size:50px">    <a href="{% url 'pizzas:pizzas' %}">Menu</a>
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}


{% block content %}
<p>
    <BODY>
        <iframe src="https://giphy.com/embed/rUtrZAGFMFjvq" width="480" height="300" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/infinite-loop-rUtrZAGFMFjvq"></a></p>
    </BODY>
    "Yeah we have infinite pizza" - Big Papa 1962-2012

    
</p>

<p>Stuff that's missing from this project: comments, user logins. I made a model, form, and view for comment stuff, but couldn't figure out how to actually implement them.</p>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}


{% block content %}
<p>
    Pizza: {{ pizza }}
</p>

<p><img src="{{ pizza.picture.url }}"></p>

<ul>
{% for t in toppings %}
<li>
    <p> {{ t.topping_name }}</p>
</li>
    {% empty %}
    <li> There are no toppings for this pizza yet. </li>
{% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}


{% block content %}
<p>
    Pizza so good, it'll make the TA of your class ignore the parts of the program that don't work.
    (too bad this place doesn't exist)
</p>

<ul>
    {% for p in pizzas %}
    <li><a href="{% url 'pizzas:pizza' p.id %}">{{ p.pizza_name }}</a> 
    </li>
    {% empty %}
    <li>No pizzas have been added yet.</li>
    {% endfor %}
</ul>


{% endblock content %}